### PR TITLE
7/6/21 (7/7/21 UTC, 1.37.9.5, 1301) update fix

### PR DESCRIPTION
**Pull request by sotakoira**
submitted wdal fixes, tested on aim_botz, seems to work fine.

before fix:

https://user-images.githubusercontent.com/63243610/125630285-375aecb3-1c64-40b1-b9a9-723832ffd47c.mp4

after fix:

https://user-images.githubusercontent.com/63243610/125630367-48fdbb83-acb7-47a0-a24e-40be276717d1.mp4

### CODE REVIEW

**Comment by abdikabirov2305** [comment]
can you recorded video guide about fix and show how fix charlotano. Please

**Comment by sotakoira** [comment]
https://github.com/sotakoira/Charlatano/archive/refs/heads/master.zip

and build it like normal charlatano

**Comment by abdikabirov2305** [comment]
This is version with fix?

**Comment by abdikabirov2305** [comment]
Record video-guide please.

**Pull request merged**
