### PR TITLE
Added toggles, color based glow esp, rage mode, hold-key for trigger,…

### PR DESCRIPTION
**Pull request by Austin72**

### CODE REVIEW

**Comment by RichHammond** [comment]
What does rage mode do?

**Comment by Austin72** [comment]
Shoots enemies in the head as soon as they are seen.

**Comment by Austin72** [comment]
I might organize this a bit more later to simplify it and make it more likely to be merged. Currently its a little messy.

**Comment by mountaser** [comment]
how can i change the rage fov ? @Austin72

**Comment by Austin72** [comment]
Currently you can't, its also limited because the game has to recognize the player as in your view.

**Comment by mountaser** [comment]
yah i realized that also its better with scope weapons like scar 
give me your hangount or telegram plz

**Comment by Austin72** [comment]
I dont have either lol, drop me your skype

**Comment by mountaser** [comment]
mountaser1998@hotmail.com

**Comment by mountaser** [comment]
hay can u send text me on skype ?

**Comment by Austin72** [comment]
Added you sorry I forgot.

**Comment by tHatsOMG** [comment]
Hi,

It's just for me or it's not finished yet ? Thanks !

:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

**Comment by Austin72** [comment]
Updating this so I will now close this pull request.

**Pull request closed without merging**
