### PR TITLE
Fix bomb overlay not correctly reporting defusability

### PR DESCRIPTION
**Pull request by RalphORama**
This pull request changes three things:

1. Cuts extra characters off of section markers in the files for settings, making them easier to read with 80 character linewrap
2. Changes the `Bomb.timeLeft()` function to return a `float` instead of an `int` for better accuracy
2. Creates and implements a netvar to check if local player has a defuser.  Before, `hasKit` in `BombTimer.kt` was always `false`, regardless of defuser possession.  Now the bomb timer overlay properly checks if a player has a defuser and lets them know they can defuse if `bomb.timeLeft() >= 5`.

### CODE REVIEW

**Comment by 10urshin** [comment]
Why would you convert it to int tho?

**Comment by Primeknight19** [comment]
Thanks RalphORama for fixing this bug

**Comment by RalphORama** [comment]
@10urshin 

"Accurate" in terms of what information is presented to the user.  My change to the overlay shows `10.932 seconds remaining` instead of `10 seconds remaining`

**Comment by Jire** [comment]
Thanks for the great work!

**Pull request merged**
