### PR TITLE
fixed skeleton esp

### PR DESCRIPTION
**Pull request by FocuzJS**
I tried intense debugging of the method you were using @Jire but a lot had changed and i didnt have a sig (or feel like making it from some guys asm dump on uc) so i wasn't able to easily debug the second half on how `IVModelInfo::GetStudiomodel` works internally specifically the jmp to `datacache.dll` but upon a little more research i found that the entity struct contains the pointer that `findStudioModel` was after.

### CODE REVIEW

**Comment by FocuzJS** [comment]
has crashed on me once, i think it may be to a game state issue? might have to partially add back some of the checks for type and valid handle since when i tested those parts of `findStudioModel` were still working fine. will update after testing further

**Comment by hcps-crewsgr** [comment]
Can someone explain on how change / fix it im a little lost

**Comment by FocuzJS** [comment]
@hcps-crewsgr read the changes in the commit tab of this pull request and you'll see the changes i made highlighted in green. you can just copy and paste or wait for @Jire to merge the PR

**Comment by hcps-crewsgr** [comment]
@FocuzJS thank you. I was lost on how to get to these files but i just had to read the file path.... LOL IM DUMB
 
also can i add you on discord?

**Comment by FocuzJS** [comment]
@GlaZex that flash has always been like that, the loop might miss a frame sometimes due to desync of the overlay and the game, but you'll notice that much more while *in-game* glow esp is applied to an entity because of how the two are different.

**Comment by GlaZex** [comment]
@FocuzJS lmao, what are you even saying. The glow shouldn't affect the overlay at all. And it isn't like the skeleton esp is desyncing, but rather it being that d3d is bad at drawing overlays. I easily fixed the problem by changing how its drawn. If you've ever seen a modern csgo cheat the you would know that blinking should *not* occur, even if its an external. Nonetheless, you get a star for trying. 🌟

**Comment by FocuzJS** [comment]
I'm saying YOU NOTICE the flicker more when you have something like glow on that doesn't flicker......

**Comment by FocuzJS** [comment]
this isn't made with shit D3d. It's _OpenGL_. but nice try i guess

**Pull request merged**
