### PR TITLE
Hazedumper like syntax for module patterns

### PR DESCRIPTION
**Pull request by 10urshin**
So https://github.com/Jire/Charlatano/blob/f29661080bba91223ee5d6cf28a0cd19eb2b5b8c/src/main/kotlin/com/charlatano/game/offsets/ClientOffsets.kt#L76 can actually works.

Merging 2 similar code bases is not easy 😄

### CODE REVIEW

**Comment by 10urshin** [comment]
I see no difference between putting byte[] signature vs putting char[] signature in memory to be honest. Detecting byte[] is easier if anything. If your concern is interning we can just use new String() instead of literals or replace it with gibberish after read using unsafe;

http://mishadoff.com/blog/java-magic-part-4-sun-dot-misc-dot-unsafe/#hide-password

```
is String -> {
	flag.split(" ").forEach {
	if (it.trim() == "?") {
		bytes.add(0.toByte())
	} else {
		bytes.add(it.toInt(16).toByte())
	}
	val randomChar = randomInt(0, 255).toChar()
	//override string part
	val fake = flag.replaceAll(".", randomChar)
	getUnsafe().copyMemory(fake, 0L, null, toAddress(flag), sizeOf(flag));
	//override underlying char array
	val stringValue = String::class.java.getDeclaredField("value");
	stringValue.setAccessible(true);
	char[] mem = (char[]) stringValue.get(flag);
	for (i in 0 until mem.length) {
	  mem[i] = randomChar;
	}
}
```

**Comment by unlimitedsola** [comment]
The way Jire does is not `byte[]` but actually `Object[]`, much harder than you think. @10urshin

**Comment by 10urshin** [comment]
> The way Jire does is not `byte[]` but actually `Object[]`, much harder than you think. @10urshin

No I know in source code itself they are stored as Object because of vararg but in the end you are converting it to byte array with 
```
            is Number -> bytes.add(flag.toByte())
            is RepeatedInt -> repeat(flag.repeats) { bytes.add(flag.value.toByte()) }

//...

        return Offset(module, patternOffset, addressOffset, read, subtract, bytes.toByteArray())
```

In the end pattern is retained in memory as ByteArray in Offset class.

**Comment by unlimitedsola** [comment]
@10urshin oops, didn't notice that. so maybe we should fill them with zeros after pattern scanning, lol

**Comment by unlimitedsola** [comment]
anyway, I doubt whether the string literals that get compiled into class's constant pool can be erased by the way you demonstrated

**Comment by 10urshin** [comment]
Yep, It seams it cause JVM crash on 1.8 :unamused:

```
Stack: [0x000000001fa60000,0x000000001fb60000],  sp=0x000000001fb5eeb0,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0x1e34b0]
C  0x00000000031d8c67

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.misc.Unsafe.getAddress(J)J+0
j  com.onurshin.cheating.unsafestruct.unsafe.Unsafe.getAddress(J)J+5
j  com.onurshin.cheating.unsafestruct.TestKt.sizeOf(Ljava/lang/Object;)J+20
j  com.onurshin.cheating.unsafestruct.TestKt.toGibberishString(Ljava/lang/String;)V+63
j  com.onurshin.cheating.unsafestruct.TestKt$main$1.invoke()V+16
j  com.onurshin.cheating.unsafestruct.TestKt$main$1.invoke()Ljava/lang/Object;+1
j  kotlin.concurrent.ThreadsKt$thread$thread$1.run()V+4
v  ~StubRoutines::call_stub
```

Still I think this is too narrow to be considered as a detection vector, after all, even interned strings get garbage collected after a while, and I have been using it like this for a while.

**Comment by 10urshin** [comment]
Another aspect, from https://stackoverflow.com/questions/15324143/garbage-collection-of-string-literals

>  The code objects will contain one or more references to the String objects that represent the literals. So as long as the code objects are reachable, the String objects will be to.
> 
> It is possible for code objects to become unreachable, but only if they were dynamically loaded ... and their classloader is destroyed.

Why not put signatures in kts files then? We can load them from kts using Dojo and discard the class loader of Dojo after we get the bytearray signature.

**Comment by Jire** [comment]
@10urshin Signatures in kts sounds like a better solution and introduces additional flexibility for the users 😄

**Comment by 10urshin** [comment]
Well since in my private implementation I already have an user interface and got rid of the Dojo, I won't be implementing this, It was just a suggestion 😄 

Anyway you might wanna revert to hardcoded pstudiohdr address @Jire, since I broke it in last commit.

**Pull request closed without merging**
