### PR TITLE
Added toggleESP (alt+0)

### PR DESCRIPTION
**Pull request by MShoaei**
Added in-game ESP toggle feature. can be improved to support other scripts, too.

### CODE REVIEW

**Comment by 10urshin** [comment]
+5,799 −1 for a 20 lines feature? 😅 And do you really need to poll it every 10 ms ?

**Comment by Jire** [comment]
I can't accept this because you included an excess of binary files and config files; please only commit the necessary files to change.

Fundamentally though, I think it'd be better to provide toggling with hotkeys for every script. In the works right now, with a little different script system implementation, due for 1.1.0 😃

**Comment by 10urshin** [comment]
In that case I can post my toggles as a suggestion.

Off topic: Any ETA for 1.1.0?

```

import com.charlatano.settings.*
import com.charlatano.utils.ObservableBoolean
import com.charlatano.utils.every
import org.jire.arrowhead.keyPressed
import java.awt.event.KeyEvent


private val toggles = arrayListOf(
        Toggle("AIM", { ENABLE_AIM }, { ENABLE_AIM = it }, { keyPressed(TOGGLE_KEY_AIM) }, { HOLD_TOGGLE_AIM }),
        Toggle("BUNNY_HOP", { ENABLE_BUNNY_HOP }, { ENABLE_BUNNY_HOP = it }, { keyPressed(TOGGLE_KEY_BUNNYHOP) }, { HOLD_TOGGLE_BUNNYHOP }),
        Toggle("ESP", { ENABLE_ESP }, { ENABLE_ESP = it; }, { keyPressed(TOGGLE_KEY_ESP) }, { HOLD_TOGGLE_ESP }),
        Toggle("RAGE", { ENABLE_RAGE }, { ENABLE_RAGE = it }, { keyPressed(TOGGLE_KEY_RAGE) }, { HOLD_TOGGLE_RAGE }),
        Toggle("RCS", { ENABLE_RCS }, { ENABLE_RCS = it }, { keyPressed(TOGGLE_KEY_RCS) }, { HOLD_TOGGLE_RCS }),
        Toggle("BONE_TRIGGER", { ENABLE_BONE_TRIGGER }, { ENABLE_BONE_TRIGGER = it }, { keyPressed(TOGGLE_KEY_BONETRIGGER) }, { HOLD_TOGGLE_BONETRIGGER }),
        Toggle("AIM_AT_HEAD", { AIM_AT_HEAD }, { AIM_AT_HEAD = it }, { keyPressed(TOGGLE_KEY_AIM_AT_HEAD) }, { HOLD_TOGGLE_AIM_AT_HEAD })
)


fun toggles() = every(300) {
    for(i in 0 until toggles.size){
        toggles[i].update()
    }
}


class Toggle(val name: String,
             private val getToggle: () -> Boolean,
             private val updateToggle: (Boolean) -> Unit,
             updateKeyState: () -> Boolean,
             private val hold: () -> Boolean) : ObservableBoolean(updateKeyState) {

    override fun update() {
        super.update()
        if (hold.invoke()) {
            updateValue(isTrue)
        } else if (keyPressed(KeyEvent.VK_ALT) && toggleKeyIsJustPressed()) {
            updateValue(!getToggle.invoke())
        }
    }

    private fun updateValue(newValue: Boolean) {
        if (getToggle.invoke() != newValue) {
            updateToggle.invoke(newValue)
        }
    }

    private fun toggleKeyIsJustPressed() = justBecomeTrue()

    private fun toggleKeyIsJustReleased() = justBecomeFalse()
}
open class ObservableBoolean(private val updateState: () -> Boolean,
                             var wasTrue: Boolean = updateState(),
                             var isTrue: Boolean = wasTrue) {
    open fun update() {
        wasTrue = isTrue
        isTrue = updateState()
    }

    fun justBecomeTrue(): Boolean {
        return !wasTrue && isTrue
    }

    fun justBecomeFalse(): Boolean {
        return wasTrue && !isTrue
    }
}
```

**Comment by MShoaei** [comment]
Yeah, sorry for the not standard pull request! 😢 This was my first time doing this. I guess it would be better to make an issue but seeing a lot of open and closed issues related to this problem encouraged me to implement a simple version of old solutions. Also in my opinion this would be a very cool feature to add, ASAP :D

**Comment by MShoaei** [comment]
Is there any point in making a new pull request? Or maybe create a new branch and accept this as a temporary fix for the problem.

**Pull request closed without merging**
