### PR TITLE
1345 build rcs fix

### PR DESCRIPTION
**Pull request by sotakoira**

### CODE REVIEW

**Comment by giaanh6002** [comment]
please update for path aim pls , aimbot dont work
love you

**Comment by sotakoira** [comment]
> 
> 
> please update for path aim pls , aimbot dont work
> love you

https://user-images.githubusercontent.com/63243610/134612749-49aa1048-42a7-418f-9272-7960ee42f375.mp4

works on my end, no need to update anything further

**Comment by giaanh6002** [comment]
Mine dont work do u have discord i will dm you for more

**Comment by spintowin1** [comment]
Problem solve i was download ur version but setting in advenced 64 work 128 tick dont work

**Comment by sotakoira** [comment]
changing the tickrate to 128 in advanced.kts works fine

https://user-images.githubusercontent.com/63243610/134661696-a50769c8-afe8-4762-bf93-12d57310f786.mp4

most likely some external anticheat is blocking the cheat from loading properly
not like this is vac detected and i already have to use vac bypass with it

**Comment by spintowin1** [comment]
Idk my problem is but it work now thank u

**Pull request merged**
